package com.payment.replay.parser;

import com.payment.replay.model.ReplayMessage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.Consumer;

/**
 * Reads sanitized output files generated by the filter-mask command.
 * Parses records back into ReplayMessage objects ready for MQ replay.
 *
 * The sanitized file format mirrors the original log format but with
 * masked data and UAT BIC codes.
 *
 * Format:
 * <datetime>,mq,<direction>,<bank bic>,<switch>,<MsgType>,<valid>,<instraId>,<MsgId>...<QueueName>...<XML>
 */
public final class SanitizedFileReader {

    private static final Logger log = LoggerFactory.getLogger(SanitizedFileReader.class);

    private static final String FIELD_SEPARATOR = "...";
    private static final String LOG_FILE_PREFIX = "raw-";
    private static final String LOG_FILE_EXTENSION = ".log";
    private static final String[] SWITCH_FOLDERS = {"sw1", "sw2", "sw3", "sw4"};

    /**
     * Reads all sanitized files from the input directory and returns ReplayMessage objects.
     * Processes all switch folders (sw1-sw4) under the input directory.
     *
     * @param inputDirectory path to the sanitized output directory
     * @return list of all replay messages, unsorted
     */
    public List<ReplayMessage> readAllMessages(String inputDirectory) {
        List<ReplayMessage> messages = new ArrayList<>();
        readAllMessages(inputDirectory, messages::add);
        return messages;
    }

    /**
     * Streams all sanitized files, invoking consumer for each valid record.
     * Memory-efficient for large datasets.
     *
     * @param inputDirectory path to the sanitized output directory
     * @param consumer callback for each ReplayMessage
     */
    public void readAllMessages(String inputDirectory, Consumer<ReplayMessage> consumer) {
        Path rootDir = Paths.get(inputDirectory);

        if (!Files.exists(rootDir)) {
            log.error("Sanitized input directory does not exist: {}", inputDirectory);
            return;
        }

        for (String switchFolder : SWITCH_FOLDERS) {
            Path switchDir = rootDir.resolve(switchFolder);
            if (Files.exists(switchDir) && Files.isDirectory(switchDir)) {
                readSwitchFolder(switchDir, consumer);
            }
        }
    }

    /**
     * Reads all sanitized files from a single switch folder.
     */
    private void readSwitchFolder(Path switchDir, Consumer<ReplayMessage> consumer) {
        List<Path> files = listLogFiles(switchDir);

        for (Path file : files) {
            readSingleFile(file, consumer);
        }
    }

    /**
     * Reads a single sanitized file line by line, parsing each into a ReplayMessage.
     *
     * @param filePath path to the sanitized log file
     * @param consumer callback for each successfully parsed message
     */
    public void readSingleFile(Path filePath, Consumer<ReplayMessage> consumer) {
        String sourceFile = filePath.toString();
        long lineNumber = 0;
        long successCount = 0;

        log.debug("Reading sanitized file: {}", sourceFile);

        try (BufferedReader reader = Files.newBufferedReader(filePath, StandardCharsets.UTF_8)) {
            String line;
            while ((line = reader.readLine()) != null) {
                lineNumber++;

                if (line.trim().isEmpty()) {
                    continue;
                }

                ReplayMessage message = parseSanitizedLine(line, sourceFile, lineNumber);
                if (message != null) {
                    consumer.accept(message);
                    successCount++;
                }
            }
        } catch (IOException e) {
            log.error("Error reading sanitized file {}: {}", sourceFile, e.getMessage());
        }

        log.debug("Read {} messages from {}", successCount, sourceFile);
    }

    /**
     * Parses a sanitized log line into a ReplayMessage.
     * Returns null for lines that don't match the expected format.
     *
     * @param line       sanitized log line
     * @param sourceFile source file for error context
     * @param lineNumber line number for error context
     * @return ReplayMessage or null if parsing fails
     */
    ReplayMessage parseSanitizedLine(String line, String sourceFile, long lineNumber) {
        if (!line.contains(",mq,") || !line.contains(FIELD_SEPARATOR)) {
            return null;
        }

        try {
            int firstSeparator = line.indexOf(FIELD_SEPARATOR);
            int secondSeparator = line.indexOf(FIELD_SEPARATOR, firstSeparator + FIELD_SEPARATOR.length());

            if (secondSeparator < 0) {
                log.trace("Missing second separator at {}:{}", sourceFile, lineNumber);
                return null;
            }

            String metadataPart = line.substring(0, firstSeparator);
            String queueName = line.substring(firstSeparator + FIELD_SEPARATOR.length(), secondSeparator).trim();
            String xmlPayload = line.substring(secondSeparator + FIELD_SEPARATOR.length()).trim();

            String[] fields = metadataPart.split(",", -1);
            if (fields.length < 9) {
                log.trace("Insufficient fields at {}:{}", sourceFile, lineNumber);
                return null;
            }

            // Extract site number from queue name (e.g., G3_1 -> "1")
            String siteNumber = extractSiteNumber(queueName);

            return ReplayMessage.builder()
                    .timestamp(fields[0].trim())
                    .bankBic(fields[3].trim())
                    .queueName(queueName)
                    .siteNumber(siteNumber)
                    .xmlPayload(xmlPayload)
                    .messageId(fields[8].trim())
                    .instructionId(fields[7].trim())
                    .sourceFile(sourceFile)
                    .lineNumber(lineNumber)
                    .build();

        } catch (Exception e) {
            log.trace("Failed to parse sanitized line at {}:{} - {}", sourceFile, lineNumber, e.getMessage());
            return null;
        }
    }

    /**
     * Extracts site number from queue name pattern: BANK_REQUEST.TO.G3_<siteNo>
     */
    private String extractSiteNumber(String queueName) {
        if (queueName == null || !queueName.contains("G3_")) {
            return "1";
        }
        int idx = queueName.lastIndexOf("G3_");
        return queueName.substring(idx + 3);
    }

    /**
     * Lists log files in a directory matching the naming convention.
     */
    private List<Path> listLogFiles(Path directory) {
        List<Path> files = new ArrayList<>();
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(directory, path -> {
            String name = path.getFileName().toString().toLowerCase();
            return Files.isRegularFile(path)
                    && name.startsWith(LOG_FILE_PREFIX)
                    && name.endsWith(LOG_FILE_EXTENSION);
        })) {
            for (Path file : stream) {
                files.add(file);
            }
        } catch (IOException e) {
            log.error("Error listing files in {}: {}", directory, e.getMessage());
        }

        Collections.sort(files, (a, b) -> a.getFileName().toString().compareTo(b.getFileName().toString()));
        return files;
    }
}
