package com.payment.replay.parser;

import com.payment.replay.model.ReplayMessage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.Consumer;

/**
 * Reads sanitized output files generated by the filter-mask command.
 * Parses each line back into a ReplayMessage for MQ replay.
 *
 * Sanitized file format (13 comma-separated fields):
 *
 *   [0]  datetime
 *   [1]  "mq"
 *   [2]  direction
 *   [3]  UAT bank BIC
 *   [4]  switch name
 *   [5]  message type
 *   [6]  "valid"
 *   [7]  instruction ID
 *   [8]  message ID
 *   [9]  "iso20022"
 *   [10] "raw"
 *   [11] masked XML payload  (may contain commas)
 *   [12] derived queue name  (e.g. DBSSSGS0_REQUEST.TO.G3_1)
 *
 * The queue name was written by FilterMaskCommand as the final field so replay
 * never needs to reconstruct it.
 */
public final class SanitizedFileReader {

    private static final Logger log = LoggerFactory.getLogger(SanitizedFileReader.class);

    private static final int    MIN_FIELDS      = 13;
    private static final int    XML_FIELD_INDEX = 11;
    private static final String LOG_FILE_PREFIX = "raw-";
    private static final String LOG_FILE_EXT    = ".log";
    private static final String[] SWITCH_FOLDERS = {"sw1", "sw2", "sw3", "sw4"};

    /**
     * Reads all sanitized messages from every switch folder under inputDirectory.
     * Convenience method that collects into a list.
     */
    public List<ReplayMessage> readAllMessages(String inputDirectory) {
        List<ReplayMessage> messages = new ArrayList<>();
        readAllMessages(inputDirectory, messages::add);
        return messages;
    }

    /**
     * Streams all sanitized messages, invoking consumer for each valid record.
     * Memory-efficient for large datasets.
     */
    public void readAllMessages(String inputDirectory, Consumer<ReplayMessage> consumer) {
        Path rootDir = Paths.get(inputDirectory);
        if (!Files.exists(rootDir)) {
            log.error("Sanitized input directory does not exist: {}", inputDirectory);
            return;
        }
        for (String folder : SWITCH_FOLDERS) {
            Path switchDir = rootDir.resolve(folder);
            if (Files.exists(switchDir) && Files.isDirectory(switchDir)) {
                for (Path file : listLogFiles(switchDir)) {
                    readSingleFile(file, consumer);
                }
            }
        }
    }

    /**
     * Reads a single sanitized file, parsing each line into a ReplayMessage.
     */
    public void readSingleFile(Path filePath, Consumer<ReplayMessage> consumer) {
        String src = filePath.toString();
        long lineNo = 0;
        long ok = 0;

        log.debug("Reading sanitized file: {}", src);

        try (BufferedReader reader = Files.newBufferedReader(filePath, StandardCharsets.UTF_8)) {
            String line;
            while ((line = reader.readLine()) != null) {
                lineNo++;
                if (line.trim().isEmpty()) continue;

                ReplayMessage msg = parseLine(line, src, lineNo);
                if (msg != null) {
                    consumer.accept(msg);
                    ok++;
                }
            }
        } catch (IOException e) {
            log.error("Error reading sanitized file {}: {}", src, e.getMessage());
        }

        log.debug("Read {} messages from {}", ok, src);
    }

    /**
     * Parses one sanitized output line into a ReplayMessage.
     *
     * The queue name is the last (13th) field written by FilterMaskCommand.
     * The site number is extracted from the queue name suffix _G3_1 / _G3_2.
     *
     * Returns null if the line doesn't match the expected format.
     */
    ReplayMessage parseLine(String line, String sourceFile, long lineNumber) {
        if (!line.contains(",mq,")) {
            return null;
        }

        // Split into MIN_FIELDS parts; the XML (field 11) may itself contain commas,
        // so we must split into exactly MIN_FIELDS tokens — field 11 absorbs everything
        // between the 11th and 12th delimiter, leaving field 12 as the queue name.
        String[] fields = line.split(",", MIN_FIELDS);

        if (fields.length < MIN_FIELDS) {
            log.trace("Insufficient fields ({}) at {}:{}", fields.length, sourceFile, lineNumber);
            return null;
        }

        String timestamp   = fields[0].trim();
        String bankBic     = fields[3].trim();
        String messageId   = fields[8].trim();
        String instrId     = fields[7].trim();
        String xmlPayload  = fields[XML_FIELD_INDEX].trim();
        String queueName   = fields[MIN_FIELDS - 1].trim();      // field 12

        String siteNumber  = extractSiteNumber(queueName);

        return ReplayMessage.builder()
                .timestamp(timestamp)
                .bankBic(bankBic)
                .queueName(queueName)
                .siteNumber(siteNumber)
                .xmlPayload(xmlPayload)
                .messageId(messageId)
                .instructionId(instrId)
                .sourceFile(sourceFile)
                .lineNumber(lineNumber)
                .build();
    }

    /** Extracts the site number from a queue name pattern: BANK_REQUEST.TO.G3_&lt;n&gt; */
    private String extractSiteNumber(String queueName) {
        if (queueName == null || !queueName.contains("G3_")) {
            return "1";
        }
        int idx = queueName.lastIndexOf("G3_");
        return queueName.substring(idx + 3);
    }

    private List<Path> listLogFiles(Path directory) {
        List<Path> files = new ArrayList<>();
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(directory, p -> {
            String n = p.getFileName().toString().toLowerCase();
            return Files.isRegularFile(p) && n.startsWith(LOG_FILE_PREFIX) && n.endsWith(LOG_FILE_EXT);
        })) {
            for (Path f : stream) files.add(f);
        } catch (IOException e) {
            log.error("Error listing files in {}: {}", directory, e.getMessage());
        }
        Collections.sort(files, (a, b) -> a.getFileName().toString().compareTo(b.getFileName().toString()));
        return files;
    }
}
