package com.payment.replay.command;

import com.payment.replay.config.AppConfig;
import com.payment.replay.logging.ErrorReporter;
import com.payment.replay.logging.MetricsCollector;
import com.payment.replay.model.ProcessingMetrics;
import com.payment.replay.replay.ReplayOrchestrator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Functionality 2: Time-Based MQ Message Replay
 *
 * Reads sanitized output files (generated by filter-mask command),
 * groups messages by time interval, and replays them to IBM MQ
 * respecting the original timing pattern and rate limits.
 *
 * Usage:
 *   java -jar payment-replay-tool.jar replay <logpath>
 *
 * Where <logpath> is the directory containing sanitized files
 * (typically the output directory from filter-mask).
 */
public final class ReplayCommand implements Command {

    private static final Logger log = LoggerFactory.getLogger(ReplayCommand.class);

    private final AppConfig config;
    private final ReplayOrchestrator replayOrchestrator;
    private final MetricsCollector metricsCollector;
    private final ErrorReporter errorReporter;

    public ReplayCommand(AppConfig config,
                         ReplayOrchestrator replayOrchestrator,
                         MetricsCollector metricsCollector,
                         ErrorReporter errorReporter) {
        this.config = config;
        this.replayOrchestrator = replayOrchestrator;
        this.metricsCollector = metricsCollector;
        this.errorReporter = errorReporter;
    }

    @Override
    public int execute(String[] args) {
        if (args.length < 1 || "--help".equals(args[0])) {
            System.out.println(getUsage());
            return args.length < 1 ? 1 : 0;
        }

        String inputDirectory = args[0];
        ProcessingMetrics metrics = new ProcessingMetrics();

        log.info("=== Replay Command Started ===");
        log.info("Input directory: {}", inputDirectory);
        log.info("Grouping interval: {}s", config.getReplayConfig().getGroupingIntervalSeconds());
        log.info("Max messages/sec: {}", config.getReplayConfig().getMaxMessagesPerSecond());

        try {
            // Execute replay
            replayOrchestrator.replay(inputDirectory, metrics);

            // Finalize metrics
            metrics.markComplete();
            metricsCollector.reportMetrics(metrics);
            errorReporter.flush();

            log.info("=== Replay Command Completed ===");
            log.info("Duration: {}ms", metrics.getDurationMs());
            log.info("Messages sent: {}", metrics.getRecordsSentToMq());
            log.info("MQ failures: {}", metrics.getMqFailures());

            printSummary(metrics);
            printPerMinuteReport(metrics);

            return metrics.getMqFailures() > 0 ? 1 : 0;

        } catch (Exception e) {
            log.error("Fatal error during replay: {}", e.getMessage(), e);
            System.err.println("Error: " + e.getMessage());
            return 2;
        }
    }

    /**
     * Prints a processing summary to stdout.
     */
    private void printSummary(ProcessingMetrics metrics) {
        System.out.println();
        System.out.println("=== Replay Summary ===");
        System.out.printf("  Messages sent to MQ:   %d%n", metrics.getRecordsSentToMq());
        System.out.printf("  MQ failures:           %d%n", metrics.getMqFailures());
        System.out.printf("  Duration:              %dms%n", metrics.getDurationMs());
        System.out.printf("  Throughput:            %.1f messages/sec%n", metrics.getThroughput());
        System.out.println();
    }

    /**
     * Prints per-minute statistics showing Read/Sent/Failed counts.
     */
    private void printPerMinuteReport(ProcessingMetrics metrics) {
        if (metrics.getMinuteMetrics().isEmpty()) {
            return;
        }

        System.out.println("=== Per-Minute Statistics ===");
        System.out.printf("  %-10s %-10s %-10s %-10s%n", "Time", "Read", "Sent", "Failed");
        System.out.println("  " + String.join("", java.util.Collections.nCopies(40, "-")));

        metrics.getMinuteMetrics().entrySet().stream()
                .sorted(java.util.Map.Entry.comparingByKey())
                .forEach(entry -> {
                    ProcessingMetrics.MinuteMetrics mm = entry.getValue();
                    System.out.printf("  %-10s %-10d %-10d %-10d%n",
                            entry.getKey(), mm.getRead(), mm.getSent(), mm.getFailed());
                });

        System.out.println();
    }

    @Override
    public String getName() {
        return "replay";
    }

    @Override
    public String getDescription() {
        return "Replay sanitized XML messages to IBM MQ with time-based scheduling";
    }

    @Override
    public String getUsage() {
        return "Usage: java -jar payment-replay-tool.jar replay <logpath>\n" +
                "\n" +
                "Arguments:\n" +
                "  <logpath>    Directory containing sanitized files (output of filter-mask)\n" +
                "\n" +
                "Description:\n" +
                "  Reads sanitized output files, groups messages by time interval,\n" +
                "  and replays them to IBM MQ respecting rate limits.\n" +
                "\n" +
                "  Messages are grouped in " + config.getReplayConfig().getGroupingIntervalSeconds() +
                "-second intervals.\n" +
                "  Maximum " + config.getReplayConfig().getMaxMessagesPerSecond() +
                " messages per second.\n" +
                "\n" +
                "  Site routing is based on the queue name pattern:\n" +
                "    <BANK>_REQUEST.TO.G3_1 -> MQ Site 1\n" +
                "    <BANK>_REQUEST.TO.G3_2 -> MQ Site 2\n" +
                "\n" +
                "Examples:\n" +
                "  java -jar payment-replay-tool.jar replay ./output\n" +
                "  java -jar payment-replay-tool.jar replay /data/sanitized/20260728";
    }
}
